### PR TITLE
 	Explanation about authenticated mode

### PR DESCRIPTION
**Pull request by stephdl**
Following this we could add a bit of documentation in the help page
http://community.nethserver.org/t/properties-of-shared-folder-not-visible/5586/9?u=stephdl

### CODE REVIEW

**Review by filippocarletti — APPROVED** [review]
Useful clarification

**Review by DavidePrincipi — COMMENTED** [review]
I'd say "Active Directory" which is more general than "Samba".

**Comment by stephdl** [comment]
Ok for me davide, just maybe we can write the full name of the rpm wanted -> nethserver-dc

**Comment by DavidePrincipi** [comment]
Done, what do you think  @stephdl ?

**Comment by stephdl** [comment]
cool, merge it, good team work :)

**Pull request merged**
